### ISSUE TITLE
New method of getting git username has small bug

### ISSUE THREAD

**Issue by twn346** [shiyanhui/FileHeader#49]
Currently, the new method of getting the git username does not work as intended. The reason is, you are calling git status and checking for an error, but `git status` is ran relative to the *process*, not the working directory of the current file. 

To see this in action, you can modify `get_user()` as follows:  

    def get_user():
    '''Get user'''

    user = getpass.getuser()
    user = os.getcwd()

    output, error = getOutputError('git status')
    if not error:
        output, error = getOutputError('git config --get user.name')
        if not error and output:
            user = output
    return user

There you can see that the current working directory is not the working directory of the current file, but of the plugin itself. 

I have a temporary fix, but i don't know if it's a good solution. 
To restore the git username detection, one option is to update the new `getOutputError` function to the following:  

    def getOutputError(cmd):
        curr_dir = sublime.active_window().extract_variables()
        curr_dir_value = sublime.expand_variables("${folder}", curr_dir)
        if curr_dir_value:
            return map(str.strip, subprocess.Popen(
                cmd, shell=True, universal_newlines=True,
                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                cwd=curr_dir_value
                ).communicate())
        else:
            return map(str.strip, subprocess.Popen(
                cmd, shell=True, universal_newlines=True,
                stdout=subprocess.PIPE, stderr=subprocess.PIPE
                ).communicate())

**Comment by shiyanhui** [comment]
That's true. I'll fix it later.

**Comment by shiyanhui** [comment]
Fixed! I will release a new version. Thank you very much!

**Comment by fupolarbear** [comment]
Hi, I encounter the same problem. I try to fix it by using the code above but FileHeader seems failed (totally stop working).

so I arbitrarily change the line:168
`output, error = getOutputError('git config --get user.name')`
to
`output, error = getOutputError('cd {0} && git config --get user.name'.format(get_dir_path()))`
and everything goes fine.

It's a temporary fix, and maybe it's not a good solution.

**Comment by shiyanhui** [comment]
Try `git config --get --global user.name` and see what will happen.

**Comment by fupolarbear** [comment]
Thank you for your response. However, I mean, I set different Git user.name between global and local repo, and when I'm working on a local repo, my FileHeader(latest version from git) still get the global user.name instead of local user.name.
